name: Bug report
description: Report a problem with vesper.nvim
labels: [bug]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "A short description of the problem you are reporting."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Neovim version"
      description: "Output of `nvim --version` (Vesper requires neovim >= 0.8)"
      render: markdown
      placeholder: |
        NVIM v0.9.0
        Build type: Release
        LuaJIT 2.1.0-beta3
    validations:
      required: false
  - type: input
    attributes:
      label: "Terminal and multiplexer"
      placeholder: "kitty 0.29.2 with tmux 3.3a"
    validations:
      required: false
  - type: input
    attributes:
      label: "Vesper version / branch / rev"
      placeholder: " v1.4.0"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce using the minimal config provided below."
      placeholder: |
        1. `nvim -u repro.lua`
        2. ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected:"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "Observed behavior (may optionally include logs, images, or videos)."
    validations:
      required: false
